Modify rofi-wifi script

diff --git a/bin/scripts/rofi-wifi b/bin/scripts/rofi-wifi
--- a/bin/scripts/rofi-wifi
+++ b/bin/scripts/rofi-wifi
@@ -1,6 +1,10 @@
 #!/bin/sh
 
-rofi_dmenu="rofi -dmenu -width 100% -i -location 1 -matching fuzzy -no-custom"
+rofi_dmenu="rofi -dmenu -width 100% -i -location 1 -matching fuzzy"
+
+failed() {
+    echo "" | $rofi_dmenu -lines 0 -p "Operation failed"
+}
 
 nmcli device wifi rescan
 bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | $rofi_dmenu -no-fixed-num-lines -p "Wifi" | cut -d' ' -f1)
@@ -10,7 +14,7 @@ bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | $rofi_dmenu -no-fixe
 pass=$(echo "" | $rofi_dmenu -lines 0 -password -p "Enter password:")
 
 if [ "$pass" = "" ]; then
-    nmcli device wifi connect $bssid
+    nmcli device wifi connect $bssid || failed
 else
-    nmcli device wifi connect $bssid password $pass
+    nmcli device wifi connect $bssid password $pass || failed
 fi
